"""add is premium user

Revision ID: 9bd84c01dec5
Revises: 800e678f3912
Create Date: 2024-03-05 17:14:21.125719+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9bd84c01dec5'
down_revision: Union[str, None] = '800e678f3912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'is_premium',
            sa.Boolean(),
            comment='Есть подписка или нет'),
        schema='common')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_premium', schema='common')
    # ### end Alembic commands ###
