"""add new column in cities

Revision ID: fde1cbcd48cf
Revises: d3831daf19a4
Create Date: 2024-03-03 12:09:50.014102+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fde1cbcd48cf'
down_revision: Union[str, None] = 'd3831daf19a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cities',
        sa.Column(
            'raw_name',
            sa.String(),
            nullable=False,
            comment='Сырое имя города'),
        schema='data')
    op.add_column(
        'cities',
        sa.Column(
            'original_name',
            sa.String(),
            nullable=True,
            comment='Оригинальное название города'),
        schema='data')
    op.drop_column('cities', 'name', schema='data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cities',
        sa.Column(
            'name',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment='Название города'),
        schema='data')
    op.drop_column('cities', 'original_name', schema='data')
    op.drop_column('cities', 'raw_name', schema='data')
    # ### end Alembic commands ###
